from enum import Enum
from typing import Any, Callable, List, Optional, Type, Union

from stories._mounted import ClassMountedStory, MountedStory

class Story:
    def __get__(self, obj: Any, cls: Any) -> Union[MountedStory, ClassMountedStory]: ...
    def __init__(self, f: Callable) -> None: ...
    def contract(self, contract: Any) -> Any: ...
    def failures(self, failures: Any) -> Optional[Union[List[str], Type[Enum]]]: ...
