from enum import Enum
from typing import Optional
from typing import Union

class StoryError: ...
class StoryDefinitionError: ...
class FailureError: ...

def make_failure_error(reason: Optional[Union[str, Enum]]) -> FailureError: ...

class FailureProtocolError: ...
class ContextContractError: ...
class MutationError: ...
